# Generated by Django 5.2.1 on 2025-07-24 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_products', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='content',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', unique=True),
        ),
    ]
