# Generated by Django 5.2.1 on 2025-07-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_products', '0002_alter_featuredproduct_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='title',
            field=models.CharField(default='hola', max_length=30),
            preserve_default=False,
        ),
    ]
